global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'bot'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:52893']

  - job_name: 'scrapper'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:53518']
