global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'what'
    static_configs:
        - targets: ["host.docker.internal:52893","host.docker.internal:53518" ]
    metrics_path: /prometheus
