global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'spring_micrometer' # The job name is assigned to scraped metrics by default.
    metrics_path: '/prometheus' # The HTTP resource path on which to fetch metrics from targets.
    static_configs: # A static_config allows specifying a list of targets and a common label set for them
        - targets: [ 'host.docker.internal:52893' ]

