spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/schedule
    username: postgres
    password: postgres
  jackson:
    time-zone: Asia/Yekaterinburg
  liquibase:
    enabled: false
  main:
    allow-bean-definition-overriding: true


app:
  codes: 429, 503
  strategy: CONSTANT
  use-queue: false



logging:
  config: classpath:log4j2-plain.xml
