spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false
management:
  prometheus:
    metrics:
      export:
        pushgateway:
          base-url: /metrics
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
      base-path: /health
  server:
    port: 53518
  wavefront:
    application:
      name: ${spring.application.name}


app:
  codes: 429, 503
  strategy: CONSTANT
server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
