app1:
  token: ${APP_TELEGRAM_TOKEN}
  codes: 429, 503
  strategy: CONSTANT
  topic: 1
  error-topic: 2
app2:
  server: localhost:9092
spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
server:
  port: 8081

logging:
  config: classpath:log4j2-plain.xml
