app1:
  token: ${APP_TELEGRAM_TOKEN}
  codes: 429, 503
  strategy: CONSTANT

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
server:
  port: 8081

management:

  prometheus:
    metrics:
      export:
        pushgateway:
          base-url: /metrics
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
      base-path:
  server:
    port: 49667



logging:
  config: classpath:log4j2-plain.xml
