app1:
  telegram-token: ${APP_TELEGRAM_TOKEN}

app:
  codes: 429, 503
  strategy: CONSTANT

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
server:
  port: 8081


logging:
  config: classpath:log4j2-plain.xml
